name: Build
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Run build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run build
        run: cargo build
        if: ${{ !cancelled() }}
