name: Test
on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run formatter
        run: cargo fmt --check
        if: ${{ !cancelled() }}

      - name: Run unit linter
        run: cargo clippy
        if: ${{ !cancelled() }}

      - name: Run unit tests
        run: cargo test
        if: ${{ !cancelled() }}
